spring.application.name=issuetracker


spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb